package(default_visibility = ["//visibility:public"])
load('/proto', 'proto_library')

proto_library(
    name = "metrics_proto",
    src = "metrics.proto",
)

cc_library(
    name = "stubs",
    hdrs = ["stubs.hh"])
