package(
    default_visibility = ["//visibility:public"])

cc_library(
    name = "container_hash_lib",
    hdrs = ["container_hash.hh"])

cc_library(
    name = "zipped_iterator_lib",
    hdrs = ["zipped_iterator.hh"])
